### ISSUE TITLE
Remove bone binding then clicking remove again crashes Spine

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#132]
See http://esotericsoftware.com/forum/Crash-caused-by-small-GUI-glitch-7318

Repro:
1. Create a mesh and a bone
2. Bind the bone to the mesh
3. Select the bound bone and press Remove
4. Notice that the Remove button remains active
5. Push the Remove button again.

```
Sorry, an unexpected error has occurred:
java.lang.RuntimeException
	at Bq.a(SourceFile:165)
	at As.a(SourceFile:34)
	at HR.a(SourceFile:394)
	at gg.a(SourceFile:28)
	at er.a(SourceFile:181)
	at er.a(SourceFile:146)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:123)
	at eS.b(SourceFile:91)
	at gi.b(SourceFile:89)
	at ex.a(SourceFile:58)
	at ez.b(SourceFile:353)
	at q.b(SourceFile:96)
	at as.b(SourceFile:91)
	at p.a(SourceFile:81)
	at ar.e(SourceFile:137)
	at ad.e(SourceFile:215)
	at nu.e(SourceFile:97)
	at ai.run(SourceFile:191)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by NathanSweet** [comment]
Should have been fixed in 3.5.05-beta.
