### ISSUE TITLE
[3.6.20 beta] Crash when moving a bone

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#187]
Repro steps:
1. Open the goblins project.
2. New Skeleton (CTRL+N).
3. New Skin on the new skeleton (double-click on skin node)
4. Drag the bone "hip" (and all its children) to the new skeleton. **CRASH**

```
java.lang.IndexOutOfBoundsException: index can't be >= size: 10 >= 10
    at hL.a(SourceFile:132)
    at AT.b(SourceFile:607)
    at AT.a(SourceFile:574)
    at com.esotericsoftware.spine.editor.Editor.b(SourceFile:785)
    at al.run(SourceFile:244)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

The crash doesn't happen if your new skeleton doesn't have any skins. You just get empty skin placeholders.
New Skin name doesn't matter.
Matching the number and names of the skins in the original skeleton still causes a crash.

New Skeleton name doesn't matter.
Images node value doesn't matter.

I'm having trouble narrowing down the cause.
I seem to only be able to repro with "hip". I think it may have something to do with #185.

**Comment by NathanSweet** [comment]
I'm unable to repro, possibly because #185 and/or #186 have been fixed.
