### ISSUE TITLE
[3.6.21 beta] Moving Linked Meshes, crash or weird stuff.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#188]
Repro project.
https://www.dropbox.com/s/tu6sjmb6bhgnrvl/goblin-debug-3_6_21.spine?dl=0
goblins-mesh modified with linked meshes for goblingirl's "left foot" and "right foot" linked to goblin's foot meshes.

 - [x] Detached linked meshes bug
Steps:
1. Make sure goblingirl skin on the original skeleton is active.
2. Drag the "hip" bone of the goblins skeleton to the new Skeleton.
3. BUG: This will successfully move most of the skeleton, (1) but the two linked meshes on goblingirl's feet no longer respond to its parent bones and (2) the "Mesh" (parent mesh) property in the properties box still shows the original parent mesh (eg, "goblin/right-foot") even if that's no longer accessible anywhere.

 - [x] Linked mesh crash
Steps:
1. Make sure goblingirl skin on the original skeleton is active.
2. Drag the "left foot" bone of the goblins skeleton to the new Skeleton. **CRASH**
Can also crash by dragging the "left foot" slot instead of bone.

```
Sorry, an unexpected error has occurred:
java.lang.NullPointerException
	at lG.a(SourceFile:93)
	at Ba.c(SourceFile:326)
	at Bk.a(SourceFile:557)
	at com.esotericsoftware.spine.editor.Editor.b(SourceFile:785)
	at al.run(SourceFile:244)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by NathanSweet** [comment]
3.6.22-beta
