### ISSUE TITLE
[3.6.21 beta] Crash when dragging an image into a Skin Placeholder.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#191]
Repro steps (drag to bone):
1. New empty project
2. Drag any image from the Images node onto the root bone. **CRASH**

Also produces crash (drag to slot):
1. New empty project
2. Add a slot to the root bone.
3. Drag any image from the Images node onto new slot. **CRASH**

Also produces crash (drag to skin placeholder):
1. New empty project
2. Create a new Skin and activate it.
3. Create a new slot and select it.
4. Choose `New...` > `Skin Placeholder`
5. Drag any image from the Images node into that new skin placeholder. **CRASH**

```
Sorry, an unexpected error has occurred:
java.lang.NullPointerException
	at BT.a(SourceFile:343)
	at com.esotericsoftware.spine.editor.Editor.b(SourceFile:819)
	at al.run(SourceFile:244)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

Does not produce crash:
- Crash does not happen when dragging an image into the viewport.
- Crash does not happen when using the `Set Parent` button on hotkey.

**Comment by Shiu** [comment]
This bug does not occur when using "Set Parent" instead of dragging.

**Comment by NathanSweet** [comment]
3.6.22-beta
