### ISSUE TITLE
[3.6.24 beta] Crash when undoing move hierarchy of bones between skeletons

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#193]
I'm still trying to look for what caused it but I have the log and sort of what I did before it happened.

- Open raptor project
- ???
- New Skeleton
- Drag the hip bone to the new skeleton.
- ??? probably nothing??
- CTRL+Z

```
Started.
Sorry, an unexpected error has occurred:
java.lang.RuntimeException: Error during hotkey: Undo: Ctrl+Z
	at pN.a(SourceFile:405)
	at mm.a(SourceFile:386)
	at p.a(SourceFile:72)
	at p.a(SourceFile:72)
	at az.a(SourceFile:312)
	at al.run(SourceFile:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 87
	at lQ.a(SourceFile:107)
	at Bv.c(SourceFile:326)
	at BF.a(SourceFile:574)
	at BF.i(SourceFile:407)
	at uA.a(SourceFile:228)
	at uA.d(SourceFile:184)
	at uy.e(SourceFile:127)
	at mJ.a(SourceFile:76)
	at pN.a(SourceFile:400)
	... 19 more
```

**Comment by NathanSweet** [comment]
Invalid array access is computing world vertices, the mesh vertices or slot deform vertices are the wrong size. Unfortunately I am unable to reproduce the crash without steps.
