### ISSUE TITLE
Import data with attachment placeholders

### ISSUE THREAD

**Issue by knifhen** [EsotericSoftware/spine-editor#271]
Hi,
I was trying to import data for a spine project containing attachment placeholders using version 3.7.03-beta and I got null pointer exceptions.

Doing the same thing in version 3.7.02-beta works fine.

- Andreas Knifh

**Comment by NathanSweet** [comment]
If you get an error, please show the error.

**Comment by knifhen** [comment]
Here is the stacktrace for the error I get.

java.lang.NullPointerException
	at com.esotericsoftware.spine.editor.Editor.a(SourceFile:909)
	at Fc.a(SourceFile:167)
	at gu.a(SourceFile:28)
	at eD.a(SourceFile:182)
	at eD.a(SourceFile:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.d(SourceFile:114)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.a_(SourceFile:132)
	at wR.a(SourceFile:167)
	at wR.b(SourceFile:154)
	at fl.a(SourceFile:92)
	at gu.a(SourceFile:28)
	at eD.a(SourceFile:182)
	at eD.a(SourceFile:153)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:124)
	at ff.a(SourceFile:92)
	at gw.a(SourceFile:89)
	at eJ.a(SourceFile:59)
	at eL.b(SourceFile:351)
	at q.b(SourceFile:96)
	at ax.b(SourceFile:91)
	at p.a(SourceFile:81)
	at aw.a(SourceFile:137)
	at ai.b(SourceFile:221)
	at mM.b(SourceFile:105)
	at an.run(SourceFile:191)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by NathanSweet** [comment]
This should be fixed in the latest (3.6.46).
