### ISSUE TITLE
[Weirdness and Crash] Error importing skeleton

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#273]
1. Tried to import user's invalid (though not at a glance?) json.
http://esotericsoftware.com/forum/3-6-41-Import-Data-doesn-t-work-with-LayersToPNG-json-9322?p=42322#p42322    
It showed this window:  
![image](https://user-images.githubusercontent.com/1911082/31089738-c48cb284-a7d7-11e7-9d69-68bcc3ee47e7.png)

2. Dismissing that window results in a weird state where the Hierarchy view is empty. But there's a selectable root bone in the viewport.
![image](https://user-images.githubusercontent.com/1911082/31089779-e837ca70-a7d7-11e7-9cfa-11d993ae0daa.png)

3. Trying to switch to animate mode results in a crash.
```
Spine Launcher 3.4.00
Windows 10 Pro x86 6.2
Java 1.7.0_80 Esoteric Software
32-bit Server VM
Up to date: Spine 3.6.41
Spine 3.6.41 Professional
[...]
Started.
java.lang.NullPointerException
	at com.esotericsoftware.spine.editor.Editor.a(SourceFile:896)
	at Fc.a(SourceFile:167)
	at gK.a(SourceFile:28)
	at eT.a(SourceFile:182)
	at eT.a(SourceFile:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.d(SourceFile:114)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.a_(SourceFile:132)
	at qY.b(SourceFile:567)
	at rh.run(SourceFile:540)
	at ak.a(SourceFile:265)
	at mK.a(SourceFile:316)
	at qH.a(SourceFile:501)
	at qH.b(SourceFile:203)
	at wU.a(SourceFile:165)
	at wZ.run(SourceFile:140)
	at uj.a(SourceFile:1658)
	at wU.b(SourceFile:133)
	at fB.a(SourceFile:92)
	at gK.a(SourceFile:28)
	at eT.a(SourceFile:182)
	at eT.a(SourceFile:153)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:124)
	at fv.a(SourceFile:92)
	at gM.a(SourceFile:89)
	at eZ.a(SourceFile:59)
	at fb.b(SourceFile:351)
	at p.b(SourceFile:96)
	at aC.a(SourceFile:332)
	at ao.run(SourceFile:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Sorry, an unexpected error has occurred:
java.lang.NullPointerException
	at com.esotericsoftware.spine.editor.Editor.a(SourceFile:896)
	at Cn.d(SourceFile:371)
	at uj.a(SourceFile:1175)
	at IH.a(SourceFile:197)
	at gK.a(SourceFile:28)
	at eT.a(SourceFile:182)
	at eT.a(SourceFile:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:124)
	at fv.a(SourceFile:92)
	at gM.a(SourceFile:89)
	at eZ.a(SourceFile:59)
	at fb.b(SourceFile:351)
	at p.b(SourceFile:96)
	at aC.a(SourceFile:332)
	at ao.run(SourceFile:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by badlogic** [comment]
Works in 3.6.43.
