### ISSUE TITLE
Unable to export Json 

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#310]
**Description of the problem**
User tries to export a JSON, but the export fails, resulting in an empty JSON file.

**Steps**

1. Open repro project
2. Press Ctrl+E
3. Select JSON export
> Settings: Extension `.json` Nonessential Data: yes; Pretty Print: yes, Create Atlas: yes.
4. click Export
Spine is stuck at 0% Export for several minutes, eventually returning to the usual setup view.
But the json is empty, and if an atlas is attempted to be exported, it's not created.
>NOTES:
>If Nonessential Data and Pretty Print are deselected, Spine will succeed exporting. (with quite some time to export)

**Repro files**
Look for "Resource.zip" in mail 160ffc661ae04a9b (the 3rd mail)

**Logs**
See mail 1 for a log from the user, here is mine:

```Spine Launcher 3.5.21
Windows 10 Education x86 6.2
Java 1.7.0_80 Esoteric Software
32-bit Server VM
Up to date: Spine 3.6.50
Spine 3.6.50 Professional
Intel
Intel(R) HD Graphics 4600
4.3.0 - Build 20.19.15.4531
Started.
java.lang.Throwable: Wl encountered uncaught exception in Wo#1
	at Wl.a(SourceFile:160)
	at com.esotericsoftware.spine.editor.Editor.b(SourceFile:820)
	at ao.run(SourceFile:244)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1248)
	at java.lang.Double.parseDouble(Double.java:540)
	at iH.a(SourceFile:243)
	at iH.a(SourceFile:39)
	at iC.a(SourceFile:1095)
	at java.lang.invoke.LambdaForm$DMH/25685568.invokeSpecial_LLI_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$NFI/7600429.invoke_LLI_L(LambdaForm$NFI)
	at java.lang.invoke.LambdaForm$DMH/31412387.invokeStatic_LL_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:1136)
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:625)
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:604)
	at java.lang.invoke.LambdaForm$LFI/14345915.interpret_L(LambdaForm$LFI)
	at java.lang.invoke.LambdaForm$MH/23200910.linkToCallSite(LambdaForm$MH)
	at ty.a(SourceFile:102)
	at java.lang.invoke.LambdaForm$DMH/22377499.invokeSpecial_LLLLIIL_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$NFI/24259801.invoke_LLLLZZL_V(LambdaForm$NFI)
	at java.lang.invoke.LambdaForm$DMH/31412387.invokeStatic_LL_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:1136)
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:625)
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:604)
	at java.lang.invoke.LambdaForm$LFI/18023535.interpret_V(LambdaForm$LFI)
	at java.lang.invoke.LambdaForm$MH/32020659.linkToCallSite(LambdaForm$MH)
	at vU.a(SourceFile:556)
	at vM.b(SourceFile:153)
	at vN.a(SourceFile:95)
	at Wo.a(SourceFile:191)
	at Wo.b(SourceFile:186)
	at VD.run(SourceFile:164)
	at Wo.a(SourceFile:199)
	at Wl.a(SourceFile:154)
	at java.lang.invoke.LambdaForm$DMH/31522323.invokeSpecial_LJ_I(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/31316977.convert(LambdaForm$MH)
```

**Comment by NathanSweet** [comment]
Added an out of memory dialog.
3.7.10-beta

**Comment by NathanSweet** [comment]
We should make pretty printing more efficient. See email 1635efda0dfea5c9 for repro project.

**Comment by NathanSweet** [comment]
3.7.17-beta
