### ISSUE TITLE
Crash when creating a new Path, first two clicks on the same spot. [3.6.52] 

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#325]
Spine Pro 3.6.52
![2018-02-28_18-24-52](https://user-images.githubusercontent.com/1911082/36782713-ba8951e6-1cb4-11e8-9e91-0765c41f1af3.gif)

Steps:
1. New project
2. Select the root bone
3. Choose `New...`>`Path`
4. Name it anything.
5. Click anywhere to create the first point.
6. Click on the same spot again. *crash*

```
Sorry, an unexpected error has occurred:
java.lang.ArrayIndexOutOfBoundsException: -4
	at CZ.a(SourceFile:19)
	at Dj.a(SourceFile:912)
	at sZ.a(SourceFile:579)
	at Eg.a(SourceFile:188)
	at sZ.a(SourceFile:102)
	at sZ.d(SourceFile:87)
	at ED.a(SourceFile:327)
	at sZ.a(SourceFile:64)
	at Eg.a(SourceFile:153)
	at mE.b(SourceFile:354)
	at p.b(SourceFile:96)
	at p.b(SourceFile:96)
	at aC.a(SourceFile:332)
	at ao.run(SourceFile:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by NathanSweet** [comment]
Good find! Fixed in 3.7.13-beta.
