### ISSUE TITLE
Leaving the Repeat field empty results in fail to export

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#336]
**Expected behavior:**
Leaving the Repeat option in gif export should make a loopable gif such as when 0 is set.

**Actual result:**
An error is thrown, no export, the error says to look at the log.

**Repro steps:**
1. Open a project
2. Press Ctrl+E
3. Select gif export
4. Select the repeat field, delete the content
5. Attempt to export

**Log:**
```
Spine Launcher 3.5.21
Windows 10 Education x86 6.2
Java 1.7.0_80 Esoteric Software
32-bit Server VM
Up to date: Spine 3.6.52
Spine 3.6.52 Professional
Intel
Intel(R) HD Graphics 4600
4.3.0 - Build 20.19.15.4531
Using customized hotkeys.
Started.
Automatic backup complete.
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.valueOf(Integer.java:582)
	at vI.a(SourceFile:279)
	at vI.b(SourceFile:140)
	at vJ.a(SourceFile:95)
	at Wa.a(SourceFile:191)
	at Wa.b(SourceFile:186)
	at Vp.run(SourceFile:164)
	at Wa.a(SourceFile:199)
	at VX.a(SourceFile:154)
	at com.esotericsoftware.spine.editor.Editor.b(SourceFile:820)
	at ao.run(SourceFile:244)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by NathanSweet** [comment]
3.7.16-beta
