### ISSUE TITLE
3.7.15 crashes on CLI export

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#339]
See mail by Marek Ledvina for repro files.

```
Spine Launcher 3.6.32
Mac OS X x86_64 10.12.6
Java 1.7.0_51 Esoteric Software
64-bit Server VM
Spine 3.7.15-beta Professional
Licensed to: Mario Zechner, contact@badlogicgames.com
Binary export: secretary_unity
ERROR: Error packing images:
java.lang.NullPointerException
	at nb.a(SourceFile:207)
	at mW.run(SourceFile:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by NathanSweet** [comment]
Sorry for the delay! Fixed in 3.7.16-beta (which will be available May 7th).
