### ISSUE TITLE
Crash when trying to parent a bone from one skeleton to the bone of another skeleton

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#341]
**Repro steps:**
1. open Spineboy-mesh
2. Make both skeletons visible and expand the skeleton to be able to see the bones
3. From the first skeleton in the list, expand the root and select the first child bone (hip)
4. press P and choose the root of the second skeleton (but also another bone will work)
> Spine crashes

**Reference mail vith Repro video:**
162dd778c6b98a9b

**Log:**
```
Spine Launcher 3.5.21
Windows 10 Education x86 6.2
Java 1.7.0_80 Esoteric Software
32-bit Server VM
Up to date: Spine 3.6.52
Spine 3.6.52 Professional
Intel
Intel(R) HD Graphics 4600
4.3.0 - Build 20.19.15.4531
Error reading hotkeys.txt file:
Invalid action: Audio View
Started.
Sorry, an unexpected error has occurred:
java.lang.RuntimeException: Bone parent has wrong skeleton: hip, spineboy-mesh != spineboy-hover
	at Ct.a(SourceFile:505)
	at Ct.i(SourceFile:456)
	at Cc.a(SourceFile:522)
	at Iv.c(SourceFile:708)
	at tc.c(SourceFile:67)
	at SM.a(SourceFile:1169)
	at fd.a(SourceFile:57)
	at eX.a(SourceFile:182)
	at eX.a(SourceFile:138)
	at ff.a(SourceFile:280)
	at p.a(SourceFile:90)
	at aC.a(SourceFile:329)
	at ao.run(SourceFile:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by erikari** [comment]
I now notice it's the same as #302

**Comment by pharan** [comment]
Is this fixed?
I tried doing this but with a different case while trying to help a forum user. It worked fine.

I'll try to do erikari's repro steps later.

**Comment by pharan** [comment]
I think this has been fixed? Should we close this issue?
Also #302

**Comment by NathanSweet** [comment]
Spineboy no longer has 2 skeletons, but duplicating the skeleton and following the repro steps doesn't crash, so I think it's been fixed.
