### ISSUE TITLE
Crash when pasting keys from one skeleton to another

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#352]
**Repro steps:**
1. open project spineboy-mesh
2. make spineboy-mesh the only skeleton visible
3. switch to animate mode
4. select all the frames of animation "run" then copy them
5. go back to setup mode
6. in skeleton spineboy-mesh select bone hip, then drag it in skeleton spineboy-hover
7. **make sure to leave skeleton spineboy-mesh and spineboy-hover visible**
8. go to animate mode
9. with animation "fly" active, paste the keyframes
> crash

**Repro gif:**
![repro gif](https://media.giphy.com/media/8qAB1PKOO03IuieQif/giphy.gif)

**Reference Thread:**
http://esotericsoftware.com/forum/Combine-project-skeletons-and-animations-into-one-10331

**Log:**
```
Spine Launcher 3.5.21
Windows 10 Enterprise x86 6.2
Java 1.7.0_80 Esoteric Software
32-bit Server VM
Up to date: Spine 3.6.52
Spine 3.6.52 Professional
Intel
Intel(R) HD Graphics 4600
4.3.0 - Build 20.19.15.4531
Error reading hotkeys.txt file:
Invalid action: Audio View
Started.
Sorry, an unexpected error has occurred:
java.lang.RuntimeException: Error during hotkey: Paste: Ctrl+V
	at qH.a(SourceFile:413)
	at mE.a(SourceFile:389)
	at p.a(SourceFile:72)
	at p.a(SourceFile:72)
	at aC.a(SourceFile:312)
	at ao.run(SourceFile:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.NullPointerException
	at mi.a(SourceFile:98)
	at Ci.c(SourceFile:330)
	at Ct.a(SourceFile:798)
	at Ct.a(SourceFile:790)
	at Ct.b(SourceFile:780)
	at Ct.a(SourceFile:765)
	at Ct.a(SourceFile:577)
	at BZ.a(SourceFile:420)
	at com.esotericsoftware.spine.editor.Editor.b(SourceFile:688)
	at com.esotericsoftware.spine.editor.Editor.f(SourceFile:680)
	at LE.q(SourceFile:1647)
	at Lr.a(SourceFile:280)
	at gQ.a(SourceFile:28)
	at eX.a(SourceFile:182)
	at eX.a(SourceFile:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.d(SourceFile:114)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.a_(SourceFile:132)
	at pV.d(SourceFile:813)
	at pV.a(SourceFile:739)
	at qH.a(SourceFile:408)
	... 19 more

```

**Comment by NathanSweet** [comment]
3.7.31-beta

**Comment by NathanSweet** [comment]
The crash was from pasting a key when the slot or bone for the key has been deleted.
