### ISSUE TITLE
Crash on skeleton duplication 

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#384]
Repro steps:
1. open file on_stage_bye.spine
2. select skeleton, 
3. click the "Duplicate" button
> crash

**Repro project:**
mail FMfcgxvzKbTbCLpqSCGMwhnPsDlghQCT

**Log:**

```
Spine Launcher 3.7.29
Esoteric Software LLC (C) 2013-2018
Windows 10 Enterprise x86 10.0, Java 10.0.2
Updating to: Spine 3.7.32-beta
Update complete.
Spine 3.7.32-beta Professional
Intel
Intel(R) HD Graphics 4600
4.3.0 - Build 20.19.15.4531
OpenAL 1.1, Default audio device
Started.
Automatic backup complete.
Automatic backup complete.
Sorry, an unexpected error has occurred:
java.lang.NullPointerException
    at EV.<init>(SourceFile:139)
    at WS.k(SourceFile:52)
    at Ru.a(SourceFile:232)
    at gR.a(SourceFile:28)
    at eX.a(SourceFile:183)
    at eX.a(SourceFile:148)
    at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:131)
    at fz.a(SourceFile:94)
    at gT.a(SourceFile:88)
    at fd.a(SourceFile:59)
    at ff.b(SourceFile:350)
    at p.b(SourceFile:124)
    at aC.a(SourceFile:342)
    at ao.run(SourceFile:254)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by NathanSweet** [comment]
3.7.33-beta
