### ISSUE TITLE
Crash on IK creation

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#422]
**Repro steps:**
1. open project "wrong.spine" from repro mail
2. select bone "IK_R_Toe"
3. choose "new IK constraint"
4. choose as target the bone "Bn_R_Foot"
> Spine crashes

**Repro project**
mail FMfcgxwBTsXXqvrpdTKHtwvJgbXfFrpp

**Repro gif:**
![gif](https://media.giphy.com/media/fUZVqyaUyqWosIboG5/giphy.gif)

**Log**
```
Spine Launcher 3.7.81
Esoteric Software LLC (C) 2013-2019
Windows 10 Enterprise x86 10.0
Up to date: Spine 3.7.85
Spine 3.7.85 Professional
Intel
Intel(R) HD Graphics 4600
4.3.0 - Build 20.19.15.4531
OpenAL 1.1, Default audio device
Started.
Sorry, an unexpected error has occurred:
java.lang.RuntimeException: Actor: gi
|  ImageTextButton
|  |  fP: icon-ok
|  |  Label: OK
|  ImageTextButton
|  |  fP: icon-cancel
|  |  Label: Cancel
	at fb.a(SourceFile:202)
	at fb.a(SourceFile:158)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:131)
	at fD.a(SourceFile:94)
	at gX.a(SourceFile:88)
	at fh.a(SourceFile:59)
	at fj.b(SourceFile:351)
	at q.b(SourceFile:124)
	at aD.a(SourceFile:344)
	at ap.run(SourceFile:259)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Shown: java.lang.Throwable
	at xt.a(SourceFile:282)
	at xt.a(SourceFile:248)
	at yN.a(SourceFile:39)
	at Ig.c(SourceFile:70)
	at uA.c(SourceFile:76)
	at uA.a(SourceFile:57)
	at Ig.a(SourceFile:44)
	at nd.b(SourceFile:330)
	at dY.b(SourceFile:209)
	at ne.b(SourceFile:362)
	at dY.b(SourceFile:183)
	at q.b(SourceFile:124)
	at q.b(SourceFile:124)
	at aD.a(SourceFile:344)
	at ap.run(SourceFile:259)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

	at xt.b(SourceFile:358)
	at fK.a(SourceFile:92)
	at gV.a(SourceFile:28)
	at fb.a(SourceFile:188)
	... 23 more
Caused by: java.lang.RuntimeException: Root bone not found for: [bone]
[root] 3285023: null  
[Bn_Pelvis] 19826482: [root] 3285023 10300925 
[IK_L_Toe] 1137790: [root] 3285023 10300925 
[IK_L_Foot] 24538372: [IK_L_Toe] 1137790 10300925 
[Bn_L_Leg] 6918957: [Bn_Pelvis] 19826482 10300925 
[Bn_L_Calf] 26182213: [Bn_L_Leg] 6918957 10300925 
[Bn_L_Foot] 29742054: [Bn_L_Calf] 26182213 10300925 
[Bn_L_Toe] 30382295: [Bn_L_Foot] 29742054 10300925 
[IK_R_Foot] 6536232: [IK_R_Toe] 33131000 10300925 
[Bn_R_Calf] 7745900: [Bn_R_Leg] 30672865 10300925 
[Bn_R_Calf] 7745900: [Bn_R_Leg] 30672865 10300925 
[Bn_R_Foot] 18728147: [Bn_R_Calf] 7745900 10300925 
[IK_R_Toe] 33131000: [root] 3285023 10300925 
[Bn_R_Leg] 30672865: [Bn_Pelvis] 19826482 10300925 
[Bn_R_Calf] 7745900: [Bn_R_Leg] 30672865 10300925 
[Bn_R_Toe] 9743268: [Bn_R_Foot] 18728147 10300925 
[bone] 19160984: [root] 3285023 10300925
	at TR.a(SourceFile:693)
	at TR.a(SourceFile:618)
	at Ii.c(SourceFile:119)
	at yN.c(SourceFile:60)
	at Ii.c(SourceFile:90)
	at xt.b(SourceFile:353)
	... 26 more
```

**Comment by NathanSweet** [comment]
3.7.86
