### ISSUE TITLE
Crash on skin placeholder deletion 

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#440]
**Steps:**
1. open the goblins project
2. select an element with a skin placeholder such as the body skinplaceholder
3. delete the skin placeholder, check `Keep all attachments`
 > crash

**Log:**

```
Spine Launcher 3.7.81
Esoteric Software LLC (C) 2013-2019
Windows 10 Enterprise x86 10.0
Up to date: Spine 3.7.91
Spine 3.7.91 Professional
4.3.0 - Build 20.19.15.4531
OpenAL 1.1, Default audio device
Started.
Sorry, an unexpected error has occurred:
java.lang.RuntimeException: Actor: gj
|  ImageTextButton
|  |  fQ: icon-ok
|  |  Label: Yes
|  ImageTextButton
|  |  fQ: icon-cancel
|  |  Label: No
	at fc.a(SourceFile:202)
	at fc.a(SourceFile:158)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:131)
	at fE.a(SourceFile:94)
	at gY.a(SourceFile:88)
	at fi.a(SourceFile:59)
	at fk.b(SourceFile:351)
	at q.b(SourceFile:124)
	at aD.a(SourceFile:349)
	at ap.run(SourceFile:259)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Shown: java.lang.Throwable
	at xA.a(SourceFile:281)
	at xA.a(SourceFile:247)
	at xt.a(SourceFile:26)
	at SB.b(SourceFile:252)
	at Vc.s(SourceFile:187)
	at TL.a(SourceFile:293)
	at gW.a(SourceFile:28)
	at fc.a(SourceFile:188)
	at fc.a(SourceFile:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:131)
	at fE.a(SourceFile:94)
	at gY.a(SourceFile:88)
	at fi.a(SourceFile:59)
	at fk.b(SourceFile:351)
	at q.b(SourceFile:124)
	at aD.a(SourceFile:349)
	at ap.run(SourceFile:259)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

	at xA.b(SourceFile:355)
	at fL.a(SourceFile:92)
	at gW.a(SourceFile:28)
	at fc.a(SourceFile:188)
	... 23 more
Caused by: java.lang.ClassCastException: java.base/[Ljava.lang.Object; cannot be cast to [LGq;
	at Tn.c(SourceFile:176)
	at xA.b(SourceFile:350)
	... 26 more

```

**Comment by Shiu** [comment]
From duplicate issue: https://github.com/EsotericSoftware/spine-editor/issues/442

*Reproduction:*
• Open Spineboy-pro
• Create a new skin
• Create a skin placeholder for the torso mesh
• Duplicate the skin (project must have at least two skins)
• Select the skin placeholder and press delete.
• Enable `keep all attachments` (this is what causes the crash to happen)
• Press `Yes` 
Spine should crash now.

gist: https://gist.github.com/Shiu/e5789bd02ef0aea2aa1d33636f76e521

**Comment by NathanSweet** [comment]
3.7.92
