### ISSUE TITLE
3.7.91 crashes on CLI export

### ISSUE THREAD

**Issue by Wizermil** [EsotericSoftware/spine-editor#443]
Hi,

I'm trying to upgrade our code to 3.7 but when I tried to export our assets with the new export json format I had this crash:

```
/Applications/Spine/Spine.app/Contents/MacOS/Spine -u 3.7.91 -i test.spine -o export_3-7-91 -e export_3-7-91.json
Spine Launcher 3.7.91
Esoteric Software LLC (C) 2013-2019 | http://esotericsoftware.com
Mac OS X x86_64 10.14.3
ERROR: Error reading export settings file:
export_3-7-91.json
java.lang.RuntimeException: Unknown object type: class ix
	at com.esotericsoftware.spine.editor.export.ExportSettings.a(SourceFile:60)
	at mU.<init>(SourceFile:72)
	at com.esotericsoftware.spine.editor.Editor.main(SourceFile:1463)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at tzax.B.run(SourceFile:2030)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

with the old export json using the old version there is no problem

```
/Applications/Spine/Spine.app/Contents/MacOS/Spine -u 3.6.53 -i test.spine -o export_3-6-53 -e export_3-6-53.json
Spine Launcher 3.7.91
Esoteric Software LLC (C) 2013-2019 | http://esotericsoftware.com
Mac OS X x86_64 10.14.3
Spine 3.6.53 Professional
Licensed to: Pretty Simple Games, seb@prettysimplegames.com
Binary export: test
Packing....................................
Writing 64x32: export_3-6-53/skeleton.png
Complete.
```
You will find attached a 3.6 test project to reproduce the issue.

[test.zip](https://github.com/EsotericSoftware/spine-editor/files/2920080/test.zip)

Thanks for your help

**Comment by NathanSweet** [comment]
Fixed in 3.7.92, thanks! Sorry for the delay getting to this.
