### ISSUE TITLE
CLI export failure

### ISSUE THREAD

**Issue by AIGRIND-LLC** [EsotericSoftware/spine-editor#495]
Hello, we updated Spine to version 3.8.74 and got an error on console export:

```
Spine -i test.spine -o export -e binary_export_settings.export.json
Spine Launcher 3.8.70
Esoteric Software LLC (C) 2013-2019 | http://esotericsoftware.com
Windows 10 Enterprise x86 10.0
Spine 3.8.74 Enterprise
Licensed to: ***, ***
Binary export: test
ERROR: Unable to start: Spine 3.8.74
ERROR: An unexpected error has occurred:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at tzax.LPT3.run(SourceFile:2231)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at Od.L(SourceFile:1789)
        at BT.L(SourceFile:41)
        at ju.L(SourceFile:95)
        at ju.L(SourceFile:69)
        at ju.L(SourceFile:54)
        at com.esotericsoftware.spine.editor.Editor.L(SourceFile:1794)
        at com.esotericsoftware.spine.editor.Editor.main(SourceFile:1755)
        ... 19 more
```       
export settings file was created by Spine editor itself. Doing export from Spine UI succeeded.
Console export with version 3.7.94 is fine.

Here is the sample project: [test.zip](https://github.com/EsotericSoftware/spine-editor/files/3708367/test.zip)

**Comment by NathanSweet** [comment]
Sorry about that! We've fixed the problem in 3.8.75, available soon. Cheers!
