### ISSUE TITLE
Crash when adding a bone to a skin

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#514]
**Repro steps:**
1. open repro project from the mail
2. in the tree, search for the bone "container"
3. select the bone container and click the button `Add to skin`
> Spine crashes

**Repro mail:**
FMfcgxwGCGxCRVVhlWvSFPqWCfWnFvSD

**Log:**
```
ERROR: An unexpected error has occurred:
java.lang.RuntimeException: Actor: ImageTextButton: icon-skinAdd Add to Skin
	at dy.S(SourceFile:202)
	at dy.S(SourceFile:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.F(SourceFile:131)
	at eb.S(SourceFile:94)
	at fv.S(SourceFile:88)
	at dE.S(SourceFile:59)
	at dG.F(SourceFile:351)
	at lpt3.F(SourceFile:124)
	at LpT4.S(SourceFile:360)
	at COm1.run(SourceFile:259)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at TU.S(SourceFile:141)
	at Xy.S(SourceFile:287)
	at ft.S(SourceFile:28)
	at dy.S(SourceFile:188)
	... 23 more
```

**Comment by NathanSweet** [comment]
3.8.78
