### ISSUE TITLE
Error "y lies outside the raster" when exporting with white space stripping enabled.

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#527]
Original report here: https://github.com/EsotericSoftware/spine-runtimes/issues/1613
Email with repro: FMfcgxwGDDqmZVZBcMCVktnQjptJSkFB

```
Spine Launcher 3.8.81
Esoteric Software LLC (C) 2013-2020 | http://esotericsoftware.com
Windows 10 Enterprise x86 10.0
Up to date: Spine 3.8.82
Spine 3.8.82 Professional
NVIDIA Corporation, GeForce RTX 2060 SUPER/PCIe/SSE2, 4.6.0 NVIDIA 442.19
Using customized hotkeys.
Started.
OpenAL 1.1, Default audio device
Automatic backup complete.
ERROR: Unable to export:
java.lang.NullPointerException
	at CA.S(SourceFile:140)
	at Cd.S(SourceFile:416)
	at Cd.C(SourceFile:386)
	at Cl.S(SourceFile:333)
	at Cl.S(SourceFile:266)
	at Cl.S(SourceFile:237)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR: Unable to export:
java.lang.NullPointerException
	at CA.S(SourceFile:140)
	at Cd.S(SourceFile:416)
	at Cd.C(SourceFile:386)
	at Cl.S(SourceFile:333)
	at Cl.S(SourceFile:266)
	at Cl.S(SourceFile:237)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)
WARNING: Error packing images:
java.awt.image.RasterFormatException: y lies outside the raster
	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(Unknown Source)
	at EH.<init>(SourceFile:38)
	at Er.S(SourceFile:49)
	at Ei.C(SourceFile:209)
	at Ei.S(SourceFile:96)
	at Ei.S(SourceFile:88)
	at EI.S(SourceFile:148)
	at Eq.S(SourceFile:96)
	at DT.S(SourceFile:255)
	at Ea.S(SourceFile:218)
	at DT.S(SourceFile:56)
	at DT.S(SourceFile:162)
	at BW.S(SourceFile:86)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)
WARNING: Error packing images:
java.awt.image.RasterFormatException: y lies outside the raster
	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(Unknown Source)
	at EH.<init>(SourceFile:38)
	at Er.S(SourceFile:49)
	at Ei.C(SourceFile:209)
	at Ei.S(SourceFile:96)
	at Ei.S(SourceFile:88)
	at EI.S(SourceFile:148)
	at Eq.S(SourceFile:96)
	at DT.S(SourceFile:255)
	at Ea.S(SourceFile:218)
	at DT.S(SourceFile:56)
	at DT.S(SourceFile:162)
	at BW.S(SourceFile:86)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR: Unable to export:
java.lang.NullPointerException
	at CA.S(SourceFile:140)
	at Cd.S(SourceFile:416)
	at Cd.C(SourceFile:386)
	at Cl.S(SourceFile:333)
	at Cl.S(SourceFile:266)
	at Cl.S(SourceFile:237)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR: Unable to export:
java.lang.NullPointerException
	at CA.S(SourceFile:140)
	at Cd.S(SourceFile:416)
	at Cd.C(SourceFile:386)
	at Cl.S(SourceFile:333)
	at Cl.S(SourceFile:266)
	at Cl.S(SourceFile:237)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by NathanSweet** [comment]
Fixed in 3.8.83 (available in a few minutes).
