### ISSUE TITLE
Crash when clicking on settings in version 3.1.05

### ISSUE THREAD

**Issue by RainySat** [EsotericSoftware/spine-editor#529]
Spine Launcher 3.8.82
Esoteric Software LLC (C) 2013-2020 | http://esotericsoftware.com
Windows 10 Enterprise 2016 LTSB x86 10.0
Update available: Spine 3.8.84
Starting: Spine 3.1.05
Spine 3.1.05 Professional, LWJGL
Error loading language: Chinese Simplified
java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(Unknown Source)
	at java.base/java.io.PushbackInputStream.read(Unknown Source)
	at gin.izh.b.<init>(Unknown Source)
	at aQ.o(SourceFile)
	at aQ.i(SourceFile:135)
	at aQ.a(SourceFile:182)
	at DQ.a(SourceFile:35)
	at DQ.<init>(SourceFile:30)
	at com.esotericsoftware.spine.editor.Editor.a(SourceFile:231)
	at ad.d(SourceFile:192)
	at ae.addNotify(SourceFile:90)
	at java.desktop/java.awt.Container.addImpl(Unknown Source)
	at java.desktop/java.awt.Container.add(Unknown Source)
	at am.c(SourceFile:135)
	at ao.run(SourceFile:96)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
NVIDIA Corporation
GeForce GTX 960/PCIe/SSE2
4.6.0 NVIDIA 431.60
Started.
Sorry, an unexpected error has occurred:
java.lang.ArrayIndexOutOfBoundsException: -1
	at hz.a(SourceFile:128)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox.e(SourceFile:277)
	at xv.a(SourceFile:186)
	at xg.a(SourceFile:481)
	at xg.ac(SourceFile:415)
	at xg.<init>(SourceFile:400)
	at qI.a(SourceFile:374)
	at gt.a(SourceFile:28)
	at eE.a(SourceFile:181)
	at eE.a(SourceFile:146)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.b(SourceFile:123)
	at fg.b(SourceFile:91)
	at gv.b(SourceFile:89)
	at eK.a(SourceFile:58)
	at eM.b(SourceFile:353)
	at o.b(SourceFile:96)
	at av.e(SourceFile:332)
	at ah.run(SourceFile:236)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by NathanSweet** [comment]
I'm afraid 3.1.05 is very old. We normally only do bug fixes for the latest version and the beta versions.

**Comment by RainySat** [comment]
This topic solved my problem[http://esotericsoftware.com/forum/3-1-05-setting-13456?p=59517#p59517](url)

**Comment by NathanSweet** [comment]
Ahh, sorry I didn't think of that. Glad it is working for you!
