### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space during packing despite sufficient system memory

### ISSUE THREAD

**Issue by cloutsocks** [EsotericSoftware/spine-editor#616]
I'm trying to do an export over cli with `Spine -Xmx16384m -u 3.8.xx ` on Windows 10 64 bit

Interestingly, the task manager memory usage never spikes, maxing out at about:

![image](https://user-images.githubusercontent.com/4283738/146258472-1e84a558-4905-408f-80c8-9cda6bf75d52.png)

So I'm at a loss what to do. Below are the logs and export settings.

```
Spine -Xmx16384m -u 3.8.xx -i "SomeFile.spine" -o "Export/Scene/" -e "Export/settings/json_pack_and_export.json"
Spine Launcher 4.1.02
Esoteric Software LLC (C) 2013-2021 | http://esotericsoftware.com
Windows 10 Pro amd64 10.0
Launching: Spine 3.8.99 Professional
Spine Launcher 4.1.02-legacy
Starting: Spine 3.8.99
Spine 3.8.99 Professional
Licensed to: [me]
NVIDIA Corporation, GeForce RTX 3060/PCIe/SSE2, 4.6.0 NVIDIA 461.92
JSON export: SomeFile
ERROR: Error packing images:
java.lang.OutOfMemoryError: Java heap space
        at java.desktop/java.awt.image.BufferedImage.getRGB(Unknown Source)
        at EA.D(SourceFile:38)
        at Fq.D(SourceFile:2306)
        at EY.D(SourceFile:96)
        at java.base/java.lang.invoke.LambdaForm$DMH/2972398.invokeSpecial(LambdaForm$DMH)
        at java.base/java.lang.invoke.LambdaForm$MH/25103431.invoke(LambdaForm$MH)
        at java.base/java.lang.invoke.LambdaForm$MH/15320859.linkToTargetMethod(LambdaForm$MH)
        at ED.D(SourceFile:256)
        at java.base/java.lang.invoke.LambdaForm$DMH/12447001.invokeStatic(LambdaForm$DMH)
        at java.base/java.lang.invoke.LambdaForm$MH/21534627.invoke(LambdaForm$MH)
        at java.base/java.lang.invoke.LambdaForm$MH/18716153.linkToTargetMethod(LambdaForm$MH)
        at EI.D(SourceFile:219)
        at ED.D(SourceFile:57)
        at ED.D(SourceFile:163)
        at java.base/java.lang.invoke.LambdaForm$DMH/28398421.invokeStatic(LambdaForm$DMH)
        at java.base/java.lang.invoke.LambdaForm$MH/21722261.invoke(LambdaForm$MH)
        at java.base/java.lang.invoke.LambdaForm$MH/17125591.linkToTargetMethod(LambdaForm$MH)
        at CE.D(SourceFile:86)
        at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(DirectMethodHandle$Holder)
        at java.base/java.lang.invoke.LambdaForm$MH/24724129.invoke(LambdaForm$MH)
        at java.base/java.lang.invoke.LambdaForm$MH/8877597.linkToTargetMethod(LambdaForm$MH)
        at AG.run(SourceFile:671)
        at java.base/java.lang.Thread.run(Unknown Source)
      
```

here is json_pack_and_export.json

```
{
"class": "export-json",
"name": "JSON",
"open": false,
"extension": ".json",
"format": "JSON",
"prettyPrint": false,
"nonessential": true,
"cleanUp": false,
"packAtlas": {
	"stripWhitespaceX": false,
	"stripWhitespaceY": false,
	"rotation": false,
	"alias": true,
	"ignoreBlankImages": false,
	"alphaThreshold": 3,
	"minWidth": 16,
	"minHeight": 16,
	"maxWidth": 16384,
	"maxHeight": 16384,
	"pot": false,
	"multipleOfFour": false,
	"square": false,
	"outputFormat": "png",
	"jpegQuality": 0.9,
	"premultiplyAlpha": false,
	"bleed": true,
	"scale": [ 1 ],
	"scaleSuffix": [ "" ],
	"scaleResampling": [ "bicubic" ],
	"paddingX": 32,
	"paddingY": 32,
	"edgePadding": true,
	"duplicatePadding": false,
	"filterMin": "Linear",
	"filterMag": "Linear",
	"wrapX": "ClampToEdge",
	"wrapY": "ClampToEdge",
	"format": "RGBA8888",
	"atlasExtension": ".atlas",
	"combineSubdirectories": false,
	"flattenPaths": false,
	"useIndexes": false,
	"debug": false,
	"fast": false,
	"limitMemory": true,
	"currentProject": true,
	"packing": "rectangles",
	"silent": false,
	"ignore": false,
	"bleedIterations": 2
},
"packSource": "attachments",
"packTarget": "perskeleton",
"warnings": true
}
```

I've also tried with binary export with the same result.

**Comment by NathanSweet** [comment]
When running 3.8.99 Spine is 32-bit and can't access more than 4GB of RAM. You can export data with 3.8.99 and then use 4.0+ to pack the texture atlas. If you choose `Legacy output`, the atlas can be used with 3.8 runtimes.

**Comment by cloutsocks** [comment]
oh wonderful, thank you!

**Comment by NathanSweet** [comment]
You're welcome! Feel free to reopen this issue if you have more trouble.

**Comment by cloutsocks** [comment]
Is there a way to pack with 4.0 for 3.8 (bypassing the memory error) using the spine file? Rather than a specific folder.

Like can I simply do a 4.0 binary export with legacy output on the packer setting and then do a 3.8 binary output overwriting the `.skel.bytes` and it works?
